apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ijap-api-hpa
  labels:
    app: ijap
    component: api
    managed-by: kustomize
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ijap-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
    # Memory-based scaling  
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    
    # Custom metrics for request rate monitoring
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 100
    
    # Queue depth monitoring
    - type: Object
      object:
        metric:
          name: rabbitmq_queue_messages
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: ijap-api
        target:
          type: Value
          value: 1000

  behavior:
    scaleUp:
      # Quick scale up for handling sudden traffic spikes
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Max
    
    scaleDown:
      # Conservative scale down to prevent thrashing
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min