# Elasticsearch configuration for IJAP Logging Cluster
# Version: 7.17.0
# Purpose: Production configuration for high-availability logging cluster

#----------------------
# Cluster Configuration
#----------------------
cluster.name: ijap-logging-cluster
node.name: ${HOSTNAME}

# High availability cluster settings
discovery.seed_hosts:
  - elasticsearch-0.elasticsearch
  - elasticsearch-1.elasticsearch
  - elasticsearch-2.elasticsearch

cluster.initial_master_nodes:
  - elasticsearch-0
  - elasticsearch-1
  - elasticsearch-2

discovery.zen.minimum_master_nodes: 2

#----------------------
# Node Configuration
#----------------------
node.master: true
node.data: true
node.ingest: true

#----------------------
# Paths Configuration
#----------------------
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

#----------------------
# Memory Configuration
#----------------------
bootstrap.memory_lock: true

# Index buffer and cache settings
indices.memory.index_buffer_size: 30%
indices.queries.cache.size: 20%
indices.fielddata.cache.size: 15%

# Circuit breaker settings
indices.breaker.total.use_real_memory: true
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 30%

#----------------------
# Network Configuration
#----------------------
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# CORS settings
http.cors.enabled: true
http.cors.allow-origin: "*"

#----------------------
# Disk Configuration
#----------------------
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%

#----------------------
# Security Configuration
#----------------------
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12

# Audit logging
xpack.security.audit.enabled: true

#----------------------
# Monitoring Configuration
#----------------------
xpack.monitoring.collection.enabled: true
xpack.monitoring.collection.interval: 30s

#----------------------
# Thread Pool Configuration
#----------------------
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000
thread_pool.get.queue_size: 1000

#----------------------
# Recovery Configuration
#----------------------
# Recovery settings for high availability
indices.recovery.max_bytes_per_sec: 40mb
indices.recovery.concurrent_streams: 4

#----------------------
# Gateway Configuration
#----------------------
gateway.recover_after_nodes: 2
gateway.expected_nodes: 3
gateway.recover_after_time: 5m

#----------------------
# Action Configuration
#----------------------
action.destructive_requires_name: true

#----------------------
# Search Configuration
#----------------------
search.max_buckets: 10000
search.default_search_timeout: 30s