apiVersion: v1
kind: ConfigMap
metadata:
  name: ijap-config
  labels:
    app: ijap
    component: config
    managed-by: kustomize
data:
  # Application Core Settings
  APP_NAME: "IJAP"
  API_VERSION: "v1"
  NODE_ENV: "production"
  API_TIMEOUT: "30"  # API request timeout in seconds
  
  # Performance Configuration
  CACHE_TTL: "900"  # Cache time-to-live in seconds (15 minutes)
  DB_TYPE: "mongodb"
  DB_CONNECTION_POOL: "50"  # Maximum database connections
  REDIS_MAX_CONNECTIONS: "100"  # Maximum Redis connections
  
  # Logging and Debugging
  ENABLE_DEBUG: "false"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW: "120"  # Time window in seconds
  RATE_LIMIT_MAX_REQUESTS: "2000"  # Maximum requests per window
  
  # Session Management
  SESSION_DURATION: "43200"  # Session duration in seconds (12 hours)
  
  # Payment Gateway Configuration
  PAYMENT_PROVIDERS: "stripe,tranzilla"
  STRIPE_API_VERSION: "2023-10"  # Stripe Connect API version
  TRANZILLA_API_VERSION: "1.0"  # Tranzilla API version
  
  # Security Settings
  CORS_ENABLED: "true"
  JWT_ALGORITHM: "RS256"
  JWT_EXPIRY: "15m"  # JWT token expiry
  REFRESH_TOKEN_EXPIRY: "7d"  # Refresh token expiry
  ENCRYPTION_ALGORITHM: "AES-256-GCM"
  TLS_VERSION: "1.3"
  
  # Internationalization
  LANGUAGES_SUPPORTED: "en,he,fr"
  DEFAULT_CURRENCY: "USD"
  SUPPORTED_CURRENCIES: "USD,EUR,ILS"
  
  # File Handling
  MAX_FILE_SIZE: "10485760"  # Maximum file size in bytes (10MB)
  ALLOWED_FILE_TYPES: "pdf,jpg,jpeg,png"
  
  # Data Management
  BACKUP_FREQUENCY: "daily"
  RETENTION_PERIOD: "7years"  # Data retention period for compliance