# Kubernetes version: v1
# Base secrets configuration for International Jewish Association Donation Platform
# This template defines secret structure to be populated by environment overlays

apiVersion: v1
kind: Secret
metadata:
  name: ijap-secrets
  namespace: ijap
  labels:
    app: ijap
    managed-by: kustomize
    security.ijap.com/encrypted: "true"
    security.ijap.com/pci-scope: "true"
    security.ijap.com/rotation-required: "true"
  annotations:
    app.kubernetes.io/part-of: ijap-platform
    app.kubernetes.io/managed-by: kustomize
    security.ijap.com/audit-level: strict
    security.ijap.com/last-rotated: ""
    security.ijap.com/rotation-schedule: "30d"
    security.ijap.com/encryption-key: ""
    vault.security.ijap.com/auto-rotate: "true"
type: Opaque
stringData:
  # Payment Gateway Credentials - Stripe Connect
  STRIPE_API_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  STRIPE_PLATFORM_ID: ""

  # Payment Gateway Credentials - Tranzilla (Israeli Market)
  TRANZILLA_TERMINAL_ID: ""
  TRANZILLA_API_KEY: ""
  TRANZILLA_API_ENDPOINT: ""
  TRANZILLA_MERCHANT_ID: ""

  # Authentication Secrets
  JWT_SECRET: ""
  JWT_REFRESH_SECRET: ""

  # Database Credentials
  DB_USERNAME: ""
  DB_PASSWORD: ""
  DB_ROOT_PASSWORD: ""

  # Cache Credentials
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""

  # Message Queue Credentials
  RABBITMQ_USERNAME: ""
  RABBITMQ_PASSWORD: ""

  # Email Service Credentials
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""

  # AWS Credentials
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: ""

  # OAuth Credentials
  OAUTH_CLIENT_ID: ""
  OAUTH_CLIENT_SECRET: ""

  # TLS Certificates
  TLS_PRIVATE_KEY: ""
  TLS_CERTIFICATE: ""

  # Backup and Recovery
  BACKUP_ENCRYPTION_KEY: ""

  # Monitoring
  MONITORING_API_KEY: ""