# Kubernetes version: v1.24+
# Purpose: Base ServiceAccount configuration for International Jewish Association Donation Platform
# Defines service accounts with enhanced security controls and cloud provider IAM integration

---
# API Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ijap-api
  labels:
    app: ijap
    component: api
    managed-by: kustomize
    security.ijap.com/monitored: "true"
    security.ijap.com/critical: "true"
  annotations:
    app.kubernetes.io/part-of: ijap-platform
    app.kubernetes.io/managed-by: kustomize
    # Security configurations
    security.ijap.com/audit-level: strict
    security.ijap.com/token-expiry: 8h
    security.ijap.com/requires-mfa: "true"
    # Cloud provider IAM role bindings
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ijap-api-role
    iam.gke.io/gcp-service-account: ijap-api@${PROJECT_ID}.iam.gserviceaccount.com
automountServiceAccountToken: true

---
# Worker Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ijap-worker
  labels:
    app: ijap
    component: worker
    managed-by: kustomize
    security.ijap.com/monitored: "true"
    security.ijap.com/critical: "true"
  annotations:
    app.kubernetes.io/part-of: ijap-platform
    app.kubernetes.io/managed-by: kustomize
    # Security configurations
    security.ijap.com/audit-level: strict
    security.ijap.com/token-expiry: 12h
    security.ijap.com/requires-mfa: "true"
    # Cloud provider IAM role bindings
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ijap-worker-role
    iam.gke.io/gcp-service-account: ijap-worker@${PROJECT_ID}.iam.gserviceaccount.com
automountServiceAccountToken: true