platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'IJAP' do
  pod 'Alamofire', '~> 5.8.0'
  pod 'Stripe', '~> 23.0'
  pod 'KeychainAccess', '~> 4.2.0'
  pod 'SwiftLint', '~> 0.52.0'
  pod 'RxSwift', '~> 6.6.0'
  pod 'RxCocoa', '~> 6.6.0'
  pod 'SDWebImage', '~> 5.18.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.0'
  pod 'Firebase/Analytics', '~> 10.0'
  pod 'Firebase/Crashlytics', '~> 10.0'
  pod 'Firebase/Messaging', '~> 10.0'
  pod 'MaterialComponents', '~> 124.2.0'

  target 'IJAPTests' do
    inherit! :search_paths
  end

  target 'IJAPUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end