apiVersion: v1
kind: ConfigMap
metadata:
  name: ijap-config
  labels:
    app: ijap
    component: config
    environment: development
    managed-by: kustomize
data:
  # Development Environment Overrides
  NODE_ENV: "development"
  API_TIMEOUT: "60"  # Extended timeout for development debugging
  CACHE_TTL: "300"  # Reduced cache TTL for development (5 minutes)
  DB_CONNECTION_POOL: "10"  # Reduced connection pool for local development
  
  # Enhanced Debugging Settings
  ENABLE_DEBUG: "true"
  LOG_LEVEL: "debug"
  
  # Relaxed Rate Limiting for Development
  RATE_LIMIT_WINDOW: "300"  # 5 minute window
  RATE_LIMIT_MAX_REQUESTS: "5000"  # Increased request limit for testing
  
  # Resource Limits
  REDIS_MAX_CONNECTIONS: "20"  # Reduced Redis connections for local environment
  
  # Extended Session Duration for Development
  SESSION_DURATION: "86400"  # 24 hours for development convenience
  
  # Development Security Settings
  CORS_ENABLED: "true"
  JWT_EXPIRY: "1h"  # Extended JWT expiry for development
  REFRESH_TOKEN_EXPIRY: "30d"  # Extended refresh token for development
  
  # Monitoring Settings
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  
  # Payment Gateway Versions
  STRIPE_API_VERSION: "2023-10"
  TRANZILLA_API_VERSION: "1.0"
  
  # Development Data Management
  BACKUP_FREQUENCY: "daily"
  RETENTION_PERIOD: "30days"  # Shorter retention for development data