apiVersion: v1
kind: ConfigMap
metadata:
  name: ijap-config
  labels:
    app: ijap
    component: config
    environment: production
    managed-by: kustomize
data:
  # Environment & Core Settings
  NODE_ENV: "production"
  API_TIMEOUT: "30"
  
  # Performance Optimization
  CACHE_TTL: "900"
  DB_CONNECTION_POOL: "100"
  REDIS_MAX_CONNECTIONS: "200"
  
  # Logging & Monitoring
  ENABLE_DEBUG: "false"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  ENABLE_DETAILED_LOGGING: "false"
  
  # Rate Limiting & Protection
  RATE_LIMIT_WINDOW: "60"
  RATE_LIMIT_MAX_REQUESTS: "10000"
  ENABLE_RATE_LIMITING: "true"
  ENABLE_REQUEST_VALIDATION: "true"
  
  # Session Management
  SESSION_DURATION: "43200"
  
  # Payment Gateway Production Settings
  STRIPE_API_VERSION: "2023-10"
  STRIPE_MODE: "live"
  TRANZILLA_MODE: "production"
  
  # Security Configuration
  CORS_ENABLED: "true"
  CORS_ORIGINS: "https://ijap.org,https://www.ijap.org"
  JWT_EXPIRY: "15m"
  REFRESH_TOKEN_EXPIRY: "7d"
  MIN_TLS_VERSION: "1.3"
  ENCRYPTION_ALGORITHM: "AES-256-GCM"
  
  # File & Data Management
  MAX_FILE_SIZE: "10485760"
  BACKUP_FREQUENCY: "daily"
  RETENTION_PERIOD: "7years"
  
  # High Availability & Scaling
  ENABLE_AUTO_SCALING: "true"
  MIN_REPLICAS: "3"
  MAX_REPLICAS: "10"
  TARGET_CPU_UTILIZATION: "70"
  
  # Circuit Breaker
  ENABLE_CIRCUIT_BREAKER: "true"
  CIRCUIT_BREAKER_TIMEOUT: "5000"